[package]
name = "sdr-heatmap"
version = "0.1.1"
authors = ["J2ghz <j2.00ghz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "^1.1.3"
image="^0.23.2"
clap="^2.33.0"
log="^0.4.8"
stderrlog="^0.4.3"
walkdir = "^2"